fotografia/cursos_app/urls.py
from django.contrib import admin
from django.urls import path , include

from .router import router

from .views import      CursosListView   \
                    ,   CursosDetailView \
                    ,   CursosCreateView \
                    ,   CursosUpdateView \
                    ,   CursosDeleteView

app_name = "cursos"

urlpatterns = [
    path("", CursosListView.as_view(), name="all"),
    path("create/", CursosCreateView.as_view(), name="create"),
    path("<int:pk>/detail/", CursosDetailView.as_view(), name="detail"),
    path("<int:pk>/update/", CursosUpdateView.as_view(), name="update"),
    path("<int:pk>/delete/", CursosDeleteView.as_view(), name="delete")
]

urlpatterns += router.urls

fotografia/fotografia_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include


from .views import IndexPage
from .views import ApiPage

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", IndexPage.as_view(), name="index"),
    path("api/", ApiPage.as_view(), name="api"),
    path("cursos/", include("cursos_app.urls"))
]

fotografia/cursos_app/models.py
from django.db import models
from django.db.models import Model

# Create your models here.
class Cursos(Model):
    """
    Atributos de clase que son usadas por herencia de la clase Model

    """
    
    nombre = models.CharField(max_length=100, default="Alumno x")
    duracion = models.CharField(max_length=100, default="Meses x", blank=False, null=False)
    contacto = models.EmailField(max_length=100, default="no_contact@mail.com")
    horario = models.CharField(max_length=100, default="Horario x")
    fecha_comienzo = models.DateField(blank=False, null=False, auto_now=True)

    # podemos crear la tabla con un nombre especifico pero se lo tenemos
    # que indicar directamente en la metaclase

    class Meta:
       db_table = "cursos_fotografia"


    def __str__(self):
        return f"El nombre del curso: {self.nombre}, dura: {self.duracion}"

    def get_fields(self):
        return [
            (field.verbose_name, field.value_from_object(self))
            for field in self.__class__._meta.fields[1:]
        ]

fotografia/cursos_app/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import View

from django.views.generic.list import ListView
from django.views.generic.edit import DeleteView, UpdateView, CreateView
from django.views.generic.detail import DetailView


from .models import Cursos

# Create your views here.


class CursosBaseView(View):
    template_name = 'cursos.html'
    model = Cursos
    fields = '__all__'
    success_url = reverse_lazy('cursos:all')


class CursosListView(CursosBaseView,ListView):
    """
    ESTO ME PERMITE CREAR UNA VISTA CON LOS Cursos
    """

class CursosDetailView(CursosBaseView,DetailView):
    template_name = "cursos_detail.html"

class CursosCreateView(CursosBaseView,CreateView):
    template_name = "cursos_create.html"
    extra_context = {
        "tipo": "Crear cursos"
    }


class CursosUpdateView(CursosBaseView,UpdateView):
    template_name = "cursos_create.html"
    extra_context = {
        "tipo": "Actualizar cursos"
    }

class CursosDeleteView(CursosBaseView,DeleteView):
    template_name = "cursos_delete.html"
    extra_context = {
        "tipo": "Borrar cursos"
    }

fotografia/fotografia_project/views.py
from django.views.generic import TemplateView

class IndexPage(TemplateView):
    template_name = "index.html"

class ApiPage(TemplateView):
    template_name = "apiIndex.html"

fotografia/cursos_app/templates/cursos.html
{% extends 'base_template.html' %}
{% load static %}
{% block content %}

<main>
    <div class="body">
        <h2>Cursos</h2>
        <h3><a href="{% url 'cursos:create' %}">Crear un curso</a></h2>
        <div class="list">
            {% for cursos in cursos_list %}
            <fieldset>
                <legend>Nombre: {{cursos.nombre}} </legend>
                <ul>
                    <li>Horario del curso: {{cursos.Horario}} </li>
                    <li>Contacto: {{cursos.Contacto}} </li>
                    <li>Duración del curso: {{cursos.duracion}} </li>
                    <li>Fecha de comienzo: {{cursos.fecha_comienzo}} </li>
                </ul>

                <div>
                    <a href="{% url 'cursos:detail' cursos.id %}">Detalle</a>
                </div>
                <div>
                    <a href="{% url 'cursos:delete' cursos.id %}">Borrar</a>
                </div>
                <div>
                    <a href="{% url 'cursos:update' cursos.id %}">Editar</a>
                </div>
            </fieldset>
            {% endfor %}
        </div>
    </div>
</main>
{% endblock %}

fotografia/cursos_app/templates/cursos_create.html
{% extends 'base_template.html' %}
{% load static %}
{% block content %}
<main>
    <div class="body">
        <form method="post">
            {% csrf_token %}
            {{form.as_div}}
            <input type="submit" value="{{ tipo}}">
        </form>
        <a href="{% url 'cursos:all' %}">Volver</a>
    </div>
</main>
{% endblock %}

fotografia/cursos_app/templates/cursos_delete.html
{% extends 'base_template.html' %}
{% block content %}

<main>
    <div class="body">
        <h2>¿Quieres borrar el curso?</h2>
        <h2> {{cursos.nombre}} </h2>
        <form method="post">
            {% csrf_token %} {{form.as_p}}
            <input type="submit" value="{{tipo}}">
        </form>
        <a href="{% url 'cursos:all' %}">Cancelar</a>
    </div>
</main>
{% endblock %}

fotografia/cursos_app/templates/cursos_detail.html
{% extends 'base_template.html' %}
{% block content %}

<main>
    <div class="body">
        <h1> {{cursos.nombre}} </h1>
        {% for label, value in cursos.get_fields %}
        <div>
            <span> {{label | upper}} </span>
            <span><b> {{value}} </b></span>
        </div>
        {%endfor%}
        <a href="{% url 'cursos:all' %}">Volver</a>
    </div>
</main>

{% endblock %}

fotografia/templates/apiIndex.html

{% load static %}
 
    <link rel="stylesheet" href="{% static './CSS/apiStyle.css' %}">
    <title>Carolina Celeste Fotografía</title>
</head>
<body>
  <header>
    <a href="index.html" class="logo"><img src="{% static './media/icons/logo.png' %}" alt=""></a>
  </header>
    <center>
        <main id="main">
            <h1>Formulario de Inspiraciones</h1>
            <hr>
            <div>
                <h3 v-show="form!=null"></h3>
                <form v-show="form!=null"></form>
                  <div v-for="(valor, item) in form">
                    <label>{{valor.label}}</label>
                    <details>{{item}}:{{quinceanera[item]}}</details>
                     <br>
                    <input
                      v-bind:type="valor.type"
                      v-bind:placeholder="valor.placeholder"
                      v-model="quinceanera[item]"
                    >
                  </div>
                  <hr>
                  <button @click="getDataHandler($event)">Cargar</button>
                </form>

                <hr>
                <p v-show="errorPost != null">{{errorPost}}</p>
            </div>
        </main>
    </center>    
</body>
<script type="module" src="{% static './js/index.js' %}"></script>
<footer>
  <a href="index.html">Volver</a><br><br>
  <p>-Carolina Celeste fotografía-</p>
</footer>
{% endblock %}

fotografia/templates/base_template.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="icon" type="image/x-icon" href="{% static './media/icons/camera.png' %}"/>


  {% block content %} {% endblock %}

</html>

fotografia/templates/index.html
{% extends 'base_template.html' %}
{% load static %}
{% block content %}     
  <link rel="stylesheet" href="{% static './CSS/style.css' %}"/>
  <title>Carolina Celeste Fotografía</title>
</head>

<body>

  <!-- navbar -->

  <header>
    <a href="#home" class="logo"><img src="{% static './media/icons/logo.png' %}" alt=""></a>
    <div class="group">
      <ul class="navigation">
        <li><a href="#home">Inicio</a></li>
        <li><a href="#about">Hola!</a></li>
        <li><a href="#packs">Packs</a></li>
        <li><a href="#form">Contacto</a></li>
      </ul>
    </div>
    <div>
      <img name="menu-outline" class="menuToggle" src="{% static './media/icons/menu.png' %}" alt="menu">
    </div>
  </header>

  <!-- Carrousel -->

  <section id="home">
    <div class="slider-frame">
      <ul>
        <li><img src="{% static './media/images/1.jpg' %}" alt=""></li>
        <li><img src="{% static './media/images/2.jpg' %}" alt=""></li>
        <li><img src="{% static './media/images/4.jpg' %}" alt=""></li>
        <li><img src="{% static './media/images/5.jpg' %}" alt=""></li>
        <li><img src="{% static './media/images/6.jpg' %}" alt=""></li>
        <li><img src="{% static './media/images/7.jpg' %}" alt=""></li>
        <li><img src="{% static './media/images/9.jpg' %}" alt=""></li>
        <li><img src="{% static './media/images/10.jpg' %}" alt=""></li>
      </ul>
    </div>
  </section>

  <!-- About -->

  <div class="about-container" id="about">
    <div class="title">
      <h1>Encantada de conocerlos</h1>
    </div>
    <div class="text-content">
      <div class="article">
        <h2>Bienvenidos!</h2>
        <p>Mi nombre es Carolina Celeste, soy fotógrafa
          de eventos,<br>familia, retratos, productos y algo más...
          <br><br>Capturando los momentos más felices<br>y memorables desde 2006
          <br><br>Acá pueden encontrar mis trabajos<br>retratando una de las
          ocasiones<br>más lindas, los 15 años
        </p>
      </div>
      <div class="about-image">
        <img src="{% static './media/images/007.jpg' %}" alt="">
      </div>
    </div>
  </div>

  <!-- Packages -->

  <section class="packages" id="packs">
    <div class="container">

      <div class="cards">
        <div class="image-section">
          <img src="{% static './media/images/01.jpg' %}" alt="pack-img" class="pack-img">
        </div>
        <div class="content">
          <h1 class="pack-name">Pack I</h1>
          <p class="description">Cobertura de todo el evento<br><br>Entrega de todas
            las tomas editadas<br>en alta, en pendrive, en caja<br><br>Fotolibro en
            tapa dura, papel fotográfico,<br>páginas rígidas, para 100 fotos</p>
        </div>
      </div>

      <div class="cards">
        <div class="image-section">
          <img src="{% static './media/images/06.jpg' %}" alt="pack-img" class="pack-img">
        </div>
        <div class="content">
          <h1 class="pack-name">Pack II</h1>
          <p class="description">Cobertura de todo el evento<br><br>Entrega de todas
            las tomas editadas<br>en alta, en pendrive, en caja<br><br>Book pre-fiesta
            <br>Libro de firmas<br><br>Fotolibro en tapa dura, papel fotográfico,
            <br>páginas rígidas, para 100 fotos
          </p>
        </div>
      </div>

      <div class="cards">
        <div class="image-section">
          <img src="{% static './media/images/03.jpg' %}" alt="pack-img" class="pack-img">
        </div>
        <div class="content">
          <h1 class="pack-name">Pack III</h1>
          <p class="description">Cobertura de todo el evento<br><br>Entrega de todas
            las tomas editadas<br>en alta, en pendrive, en caja<br><br>Book pre-fiesta
            <br>Libro de firmas<br>Video cronológico<br>Cabina fotográfica<br><br>
            Fotolibro en tapa dura, papel fotográfico,<br>páginas rígidas, para
            100 fotos
          </p>
        </div>
      </div>

    </div>
  </section>

  <!-- Form -->

  <section class="contact" id="form">
    <h1>Contacto</h1>

    <h2>Para presupuestos y consultas en general<br>
      podés llenar el formulario o enviar un mensaje a<br>
      coriacarolina@gmail.com
      <br><br><a href="https://www.instagram.com/carolina_celesteph/"><img src="{% static './media/icons/ig.png' %}"
          alt="ig"></a><br><br>
    </h2>

    <form id="form" class="form" action="https://formspree.io/f/maygvpel" method="POST">

      <label for="name"></label>
      <input type="text" id="name" name="name" placeholder="Nombre" autocomplete="off" required><br><br>
      <label for="email"></label>
      <input type="email" id="email" name="email" placeholder="Mail" autocomplete="off" required><br><br>
      <label for="date"></label>
      <input type="text" id="date" name="date" placeholder="Fecha del evento" autocomplete="off" required><br><br>
      <label for="venue"></label>
      <input type="text" id="venue" name="venue" placeholder="Nombre del salón" placeholder="Nombre del salón"
        autocomplete="off" required><br><br>
      <label for="dir"></label>
      <input type="text" id="dir" name="dir" placeholder="Localidad" autocomplete="off" required><br><br>
      <label for="pack"></label>
      <input type="text" id="pack" name="pack" placeholder="Pack 1, 2, 3 o 4" autocomplete="off"><br><br><br><br>
      <label for="message"></label>
      <textarea rows="5" cols="60" id="message" name="message" placeholder="Mensaje" autocomplete="off"
        required></textarea><br><br>

      <button type="submit" class="btn">Enviar</button>

    </form>
  </section>

  <footer>
    <a href="#home">Volver arriba</a><br><br>
    <a href="{% url 'api' %}" class="inspo">Contanos tu inspiración para la fiesta acá</a><br><br><br>
    <a href="{% url 'cursos:all' %}">Admin</a>

  </footer>

  <script>
    let navigation = document.querySelector('.navigation');
    let menuToggle = document.querySelector('.menuToggle');
    let header = document.querySelector('header');

    menuToggle.onclick = function () {
      header.classList.toggle('open');
    }
  </script>

</body>
<script src="{% static './js/index.js' %}"></script>
{% endblock %}